#!/bin/bash

dbsize=$(mongo -quiet $OPENSHIFT_MONGODB_DB_HOST:$OPENSHIFT_MONGODB_DB_PORT/$OPENSHIFT_APP_NAME -u $OPENSHIFT_MONGODB_DB_USERNAME -p $OPENSHIFT_MONGODB_DB_PASSWORD --eval "db.toilets.count()")

# If the query says that there are 0 documents then import the data
if [[ $dbsize = "0" ]]
then
	# Import the data
	mongoimport -d $OPENSHIFT_APP_NAME -c toilets --type json --file $OPENSHIFT_REPO_DIR/wellington-city-public-conveniences.json -h $OPENSHIFT_MONGODB_DB_HOST --port $OPENSHIFT_MONGODB_DB_PORT -u admin -p $OPENSHIFT_MONGODB_DB_PASSWORD

	# Make the 2dsphere index
	mongo -quiet $OPENSHIFT_MONGODB_DB_HOST:$OPENSHIFT_MONGODB_DB_PORT/$OPENSHIFT_APP_NAME -u $OPENSHIFT_MONGODB_DB_USERNAME -p $OPENSHIFT_MONGODB_DB_PASSWORD --eval 'db.toilets.ensureIndex( { geometry.coordinates : "2dsphere" } );'
	echo "Imported the data"
else
	echo "There was already data in the database. Not importing"
fi
